version: "3.9"
services:
  web:
    image: "lap"
    network_mode: "host"
    volumes:
       - /home/.docker/www/pcontrol/:/var/www/html/
       - /home/.docker/www/:/var/www/html8080/
       
  db:
    image: "postgres"
    network_mode: "host"
    volumes:
      - /home/.docker/volumes/postgresql:/var/lib/postgresql/data 



# sudo docker compose up -d
# sudo docker compose -f /LAPP -p lapp up -d
# sudo docker compose -f /LAPP -p lapp down
# sudo docker compose ps
